# Generated by Django 5.2.4 on 2025-07-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_alter_deck_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='context',
            field=models.CharField(blank=True, help_text='event | equipment | party‑fact | timeline | admission | other', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
