# Generated by Django 5.2.4 on 2025-07-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_card_context_card_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='context',
        ),
        migrations.AddField(
            model_name='card',
            name='page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
