# Generated by Django 5.2.4 on 2025-07-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_remove_card_context_card_page_alter_card_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='context',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='excerpt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
