# Generated by Django 5.2.4 on 2025-09-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_card_context_alter_card_excerpt_alter_card_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='section',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
