# Generated by Django 5.2.4 on 2025-09-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0009_add_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ordinal',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
