# Generated by Django 5.2.4 on 2025-09-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0010_card_ordinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='distractors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
